server:
  port: 9002
  servlet:
    context-path: /auth
spring:
  application:
    name: auth-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://49.235.81.235:3306/springcloud?useSSL=true&useUnicode=true&characterEncoding=gbk&serverTimezone=Hongkong
    username: kevin
    password: Kevin@12345
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
eureka:
  client:
    service-url:
      defaultZone: http://eureka-one:9000/eureka/

