server:
  port: 9000
spring:
  application:
    name: eureka-server
  profiles: eureka-server-one
eureka:
  client:
    service-url:
      defaultZone: http://eureka-two:9001/eureka/


---

server:
  port: 9001
spring:
  application:
    name: eureka-sever
  profiles: eureka-server-two
eureka:
  client:
    service-url:
      defaultZone: http://eureka-one:9000/eureka/