server:
  port: 9003
spring:
  application:
    name: gateway-server
  zipkin:
    sender:
      type: rabbit
  sleuth:
    sampler:
      probability: 1
  rabbitmq:
    host: 47.98.148.0
    port: 5672
    username: kevin
    password: 12345
eureka:
  client:
    service-url:
      defaultZone: http://eureka-one:9000/eureka/
zuul:
  routes:
    sleuthapi:
      path: /sleuth/**
      serviceId: user-client
