server:
  port: 9003
spring:
  application:
    name: gateway-server
  zipkin:
    base-url: http://localhost:9002
  sleuth:
    sampler:
      probability: 1
eureka:
  client:
    service-url:
      defaultZone: http://eureka-one:9000/eureka/
zuul:
  routes:
    sleuthapi:
      path: /sleuth/**
      serviceId: user-client
