server:
  port: 9002
spring:
  application:
    name: eureka-client
  profiles: eureka-client-one
eureka:
  client:
    service-url:
      defaultZone: http://eureka-one:9000/eureka/

---

server:
  port: 9003
spring:
  application:
    name: eureka-client
  profiles: eureka-client-two
eureka:
  client:
    service-url:
      defaultZone: http://eureka-two:9001/eureka/